### ISSUE TITLE
Enterprise Basic Security configuration and the Windows Security baseline

### ISSUE THREAD

**Issue by muradmomani** [microsoft/SecCon-Framework#12]
Hi,

currently, I'm working on security hardening of  windows 10 machines, I checked the **Windows Security Baseline**  _https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-baselines_  and come over **this repo** while reading this article _https://www.microsoft.com/security/blog/2019/04/11/introducing-the-security-configuration-framework-a-prioritized-guide-to-hardening-windows-10/_ 

so, My questions : 

1. Do implementing the security hardening using the Windows Servutiy Baseline enough without checking the L1 Enterprise Basic Security documented here? 

1. What are the main differences in security control implemented by the two approaches, are they the same or different! if different, how can you know the difference in mean of controls between the two approaches? 

Thanks

**Comment by appcompatguy** [comment]
Hi,

The SecCon framework is aligned to the Windows Security Baselines. A Level 3 configuration would include all of the policies that the baselines do (so, from a policy perspective, you'll actually be even more secure than applying Level 1). We do recommend considering other controls before applying stricter policies, which is why we developed this framework - but being more secure in some areas isn't a bad thing, our hope is to just help create a roadmap to consider all items (not just the policies with a "right" answer) when building your strategy.

Thanks!
Chris
